#!/usr/bin/env -S deno run -A
// -*- mode: typescript; -*-
/** Commands for managing a local kdesvn repository checkout. */
// vim: ft=typescript

import { existsSync, readFileSync } from "node:fs";
import { writeFile, mkdir, rm } from "node:fs/promises";
import { dirname } from "node:path";
import assert from "node:assert/strict";
import * as process from "node:process";

import { cached } from "npm:@kisaragi-hiu/cached-fetch@0.2.0";
import { $ } from "npm:zx@8.8.5";
import { program } from "npm:@commander-js/extra-typings@14.0.0";
import { z } from "npm:zod@4.1.11";

const headers = { "User-Agent": "github:kisaragi-hiu/k-gnome-l10n" };

/**
 * Write a response or string to `path`.
 * This wrapper also makes sure the directory to `path` exists.
 */
async function write(path: string, res: Response | string) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(
    path,
    typeof res === "string" ? res : new Uint8Array(await res.arrayBuffer()),
  );
}

program.description(
  `Commands for managing a local copy of GNOME translations.`,
);

/** Set up Lokalize project for `language`. */
async function initLokalize(language: string) {
  const languageObj = (await getLanguages()).find(
    ({ locale }) => locale === language,
  );
  assert(languageObj);
  await write(
    `${language}/index.lokalize`,
    `
[General]
AltDir=../REFERENCE_LANGUAGE
# BranchDir=../STABLE_TARGET
LangCode=${language}
LanguageSource=Project
PotBaseDir=../templates
# PotBranchDir=../STABLE_TEMPLATES
MailingList=MAILING_LIST
ProjLangTeam=${languageObj.name} <MAILING_LIST>
ProjectID=gnome-translation-${language}
TargetLangCode=${language}
`.trim(),
  );
}

/**
 * Download files for `languages`.
 * `existing` decides how to deal with existing files:
 * - use "delete" to delete them
 * - use "skip" to skip downloading them
 * - use "overwrite" (default) to overwrite them. If a file is deleted on the
 *   server for some reason, this will leave stale files around.
 */
async function update(
  languages: string[],
  existing: "delete" | "skip" | "overwrite" = "overwrite",
) {
  assert(new Set(languages).isSubsetOf(new Set(await getLanguageCodes())));
  const domain = "po";
  const modules = await getModules();
  const len = modules.length;
  if (existing === "delete") {
    // Delete existing translation files
    for (const lang of languages) {
      await rm(`${lang}/${domain}`, { recursive: true, force: true });
    }
    await rm(`templates/${domain}`, { recursive: true, force: true });
  }
  for (let i = 0; i < len; i++) {
    const module = modules[i];
    assert(module);
    for (const lang of languages) {
      if (existing === "skip" && existsSync(`${lang}/${domain}/${module}.po`)) {
        continue;
      }
      console.log(
        `Downloading ${lang}/${domain}/${module} (${i + 1}/${len})...`,
      );
      await downloadModule(module, lang);
    }
    if (existing === "skip" && existsSync(`templates/${domain}/${module}.po`)) {
      continue;
    }
    console.log(
      `Downloading templates/${domain}/${module} (${i + 1}/${len})...`,
    );
    await downloadModuleTemplate(module);
  }
}

// gnome-translations/<lang>/{po,help}/<module>.po
// gnome-translations/templates/{po,help}/<module>.pot
//
// Maybe: gnome-translations/stable.<lang>/<module>.po
program
  .command("init")
  .description("Initialize a translation workspace")
  .argument(
    "[dir]",
    "Where to put the translation workspace, defaults to 'gnome-translations'",
    "gnome-translations",
  )
  .option(
    "--langs <languages>",
    "Set up for these languages, as language codes. Comma-separated.",
  )
  .action(async (dir, opts) => {
    const languages = opts.langs
      ? opts.langs.split(",").map((x) => x.trim())
      : [];
    if (languages.length < 1) {
      console.log(`Please specify one or more languages with --langs`);
      process.exit(1);
    }
    if (existsSync(dir)) {
      console.log(`${dir} already exists.`);
      process.exit(1);
    }

    await mkdir(dir, { recursive: true });
    process.chdir(dir);

    assert(new Set(languages).isSubsetOf(new Set(await getLanguageCodes())));
    await writeLanguagesFile(languages);
    await update(languages);
    for (const lang of languages) {
      await initLokalize(lang);
    }
    await $`git init && git add . && git commit -m before`;
    console.log(
      `Initialized workspace at ${dir}. Remember to fill in Lokalize info`,
    );
  });

/** Write `languages` into the languages file in the current directory. */
async function writeLanguagesFile(languages: string[]) {
  await write(
    "languages",
    JSON.stringify({
      "k-gnome-l10n-//":
        "This file keeps track of which languages are checked out in this workspace.",
      languages: languages,
    }),
  );
}

program
  .command("add-language")
  .description(
    `Add a language to the current workspace.
This will redownload everything in the workspace.`,
  )
  .argument("<lang>", "New language to add")
  .action(async (newLang) => {
    assert((await getLanguageCodes()).includes(newLang));
    try {
      const languages = z
        .object({ languages: z.array(z.string()) })
        .parse(
          JSON.parse(readFileSync("languages", { encoding: "utf-8" })),
        ).languages;
      if (languages.includes(newLang)) {
        console.log(`${newLang} is already present`);
      } else {
        languages.push(newLang);
        await writeLanguagesFile(languages);
        await update(languages, "skip");
        await initLokalize(newLang);
        await $`git add . && git commit -m before`;
        console.log(`Added ${newLang}. Remember to fill in Lokalize info`);
      }
    } catch (_e) {
      console.log(
        "Unable to read file declaring currently checked out languages",
      );
    }
  });

program
  .command("update")
  .description("Pull down new translations to the current workspace")
  .option("--delete", "Delete existing files before downloading again")
  .action(async (opts) => {
    try {
      const languages = z
        .object({ languages: z.array(z.string()) })
        .parse(
          JSON.parse(readFileSync("languages", { encoding: "utf-8" })),
        ).languages;
      await update(languages, opts.delete && "delete");
      await $`git add . && git commit -m before`;
    } catch (_e) {
      console.log(
        "Unable to read file declaring currently checked out languages",
      );
    }
  });

const Modules = z.array(z.object({ name: z.string(), href: z.string() }));
/** Return a list of all module names. */
async function getModules() {
  const text = await cached("gnome-modules", () =>
    fetch("https://l10n.gnome.org/api/v1/modules/", { headers }),
  );
  return Modules.parse(JSON.parse(text)).map((x) => x.name);
}

const Module = z.object({
  name: z.string(),
  vcs_web: z.string(),
  maintainers: z.array(z.string()),
  branches: z.array(z.object({ name: z.string() })),
  domains: z.array(
    z.object({
      name: z.string(),
      description: z.string(),
      dtype: z.enum(["doc", "ui"]),
      layout: z.string(),
    }),
  ),
});
async function getModule(module: string) {
  // TODO check if module is a valid module
  const text = await cached(`gnome-module-${module}`, () =>
    fetch(`https://l10n.gnome.org/api/v1/modules/${module}`, { headers }),
  );
  return Module.parse(JSON.parse(text));
}
/** Return list of all languages with their names and codes. */
async function getLanguages() {
  const text = await cached(`gnome-languages`, () =>
    fetch(`https://l10n.gnome.org/api/v1/languages/`, { headers }),
  );
  return z
    .array(z.object({ name: z.string(), locale: z.string() }))
    .parse(JSON.parse(text));
}
/** Return list of all language codes. */
async function getLanguageCodes() {
  return (await getLanguages()).map((x) => x.locale);
}
async function moduleDefaultBranch(module: string) {
  return (await getModule(module)).branches[0]?.name;
}

/**
 * Download PO file for `module` in `language` to the right place under CWD.
 * This always downloads file for the default branch of the module.
 * `domain` specifies the domain, either "po" (UI) or "help" (docs).
 */
async function downloadModule(
  module: string,
  language: string,
  domain: "po" | "help" = "po",
) {
  assert((await getModules()).includes(module));
  assert((await getLanguageCodes()).includes(language));
  const branch = await moduleDefaultBranch(module);
  assert(branch);

  // eg. https://l10n.gnome.org/POT/gnome-terminal.gtk3/gnome-terminal.gtk3.zh_TW.po
  const res = await fetch(
    // For UI: https://l10n.gnome.org/POT/epiphany.main/epiphany.main.zh_TW.po
    // For help: https://l10n.gnome.org/POT/brasero.master/docs/brasero-help.master.zh_TW.po
    //
    // If the current translation is empty, templates that are set up beforehand
    // are also available from eg.
    // UI: https://l10n.gnome.org/module/po/epiphany/main/po/zh_TW.po
    // or help: https://l10n.gnome.org/module/po/epiphany/main/help/zh_TW.po
    // ...but I don't think we want this. Lokalize can handle creation just fine.
    domain === "po"
      ? `https://l10n.gnome.org/POT/${module}.${branch}/${module}.${branch}.${language}.po`
      : `https://l10n.gnome.org/POT/${module}.${branch}/docs/${module}-help.${branch}.${language}.po`,
    { headers },
  );
  if (res.status === 404) {
    console.log(`Downloading ${language}/${domain}/${module} returned 404`);
    return;
  }
  // like zh_TW/po/epiphany.po or ja/help/epiphany.po
  write(`${language}/${domain}/${module}.po`, res);
}

/**
 * Download template file for `module` to the right place under CWD.
 * This always downloads file for the default branch of the module.
 * `domain` specifies the domain, either "po" (UI) or "help" (docs).
 */
async function downloadModuleTemplate(
  module: string,
  domain: "po" | "help" = "po",
) {
  assert((await getModules()).includes(module));
  const branch = await moduleDefaultBranch(module);
  assert(branch);

  // For UI: https://l10n.gnome.org/POT/gnome-terminal.gtk3/gnome-terminal.gtk3.pot
  // For help: https://l10n.gnome.org/POT/brasero.master/docs/brasero-help.master.pot
  const res = await fetch(
    domain === "po"
      ? `https://l10n.gnome.org/POT/${module}.${branch}/${module}.${branch}.pot`
      : `https://l10n.gnome.org/POT/${module}.${branch}/docs/${module}-help.${branch}.pot`,
    { headers },
  );
  if (res.status === 404) {
    console.log(`Downloading templates/${domain}/${module} returned 404`);
    return;
  }
  write(`templates/${domain}/${module}.pot`, res);
}

program
  .command("get-languages")
  .description("Show language list")
  .action(async () => {
    for (const language of (await getLanguages()).sort((a, b) =>
      a.locale < b.locale ? -1 : 1,
    )) {
      console.log(`${language.locale}: ${language.name}`);
    }
  });
program
  .command("get-modules")
  .description("Show module list")
  .action(async () => {
    for (const module of await getModules()) {
      console.log(module);
    }
  });
program
  .command("get-module")
  .description("Get data about a module")
  .argument("<module>", "Module name")
  .action(async (module) => {
    console.log(`Default branch: ${await moduleDefaultBranch(module)}`);
    console.log("Other data:");
    console.log(await getModule(module));
  });

// Ignore top level errors
// If we pipe output to less then quit it without viewing the whole
// thing, the pager doesn't consume the entire pipe, which leads to a
// BrokenPipe error.
// This is the overkill but fast way to get rid of it.
program.parseAsync().catch(() => {});
