#!/usr/bin/env -S deno run -A
// -*- mode: typescript; -*-
/** Commands for managing a local kdesvn repository checkout. */
// vim: ft=typescript

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname } from "node:path";
import assert from "node:assert/strict";
import * as process from "node:process";

import { cached } from "npm:@kisaragi-hiu/cached-fetch@0.2.0";
import { Chalk } from "npm:chalk@5.6.2";
import { program } from "npm:@commander-js/extra-typings@14.0.0";
import { z } from "npm:zod@4.1.11";

const headers = { "User-Agent": "github:kisaragi-hiu/k-gnome-l10n" };

program.description(
  `Commands for managing a local copy of GNOME translations.`,
);

/**
 * Download files for `languages`.
 * Include templates if `opts.templates` is true.
 */
async function update(languages: string[]) {
  assert(new Set(languages).isSubsetOf(new Set(await getLanguages())));
  const domain = "po";
  const modules = await getModules();
  const len = modules.length;
  for (let i = 0; i < len; i++) {
    const module = modules[i];
    assert(module);
    for (const lang of languages) {
      console.log(
        `Downloading ${lang}/${domain}/${module} (${i + 1}/${len})...`,
      );
      await downloadModule(module, lang);
    }
    console.log(
      `Downloading templates/${domain}/${module} (${i + 1}/${len})...`,
    );
    await downloadModuleTemplate(module);
  }
}

// gnome-translations/<lang>/<module>.po
// gnome-translations/stable.<lang>/<module>.po
// gnome-translations/templates/<module>.pot
program
  .command("init")
  .description("Initialize a translation workspace")
  .argument(
    "[dir]",
    "Where to put the translation workspace, defaults to 'gnome-translations'",
    "gnome-translations",
  )
  .option(
    "--langs <languages>",
    "Set up for these languages, as language codes. Comma-separated.",
  )
  .action(async (dir, opts) => {
    const languages = opts.langs
      ? opts.langs.split(",").map((x) => x.trim())
      : [];
    if (languages.length < 1) {
      console.log(`Please specify one or more languages with --langs`);
      process.exit(1);
    }
    if (existsSync(dir)) {
      console.log(`${dir} already exists.`);
      process.exit(1);
    }

    await mkdir(dir, { recursive: true });
    process.chdir(dir);
    writeFileSync(
      "languages",
      JSON.stringify({
        "k-gnome-l10n-//":
          "This file keeps track of which languages are checked out in this workspace.",
        languages: languages,
      }),
    );
    await update(languages);
  });

program
  .command("update")
  .description("Pull down new translations to the current workspace")
  .action(async () => {
    try {
      const languages = z
        .object({ languages: z.array(z.string()) })
        .parse(
          JSON.parse(readFileSync("languages", { encoding: "utf-8" })),
        ).languages;
      await update(languages);
    } catch (_e) {
      console.log(
        "Unable to read file declaring currently checked out languages",
      );
    }
  });

const Modules = z.array(z.object({ name: z.string(), href: z.string() }));
/** Return a list of all module names. */
async function getModules() {
  const text = await cached("gnome-modules", () =>
    fetch("https://l10n.gnome.org/api/v1/modules/", { headers }),
  );
  return Modules.parse(JSON.parse(text)).map((x) => x.name);
}

const Module = z.object({
  name: z.string(),
  vcs_web: z.string(),
  maintainers: z.array(z.string()),
  branches: z.array(z.object({ name: z.string() })),
  domains: z.array(
    z.object({
      name: z.string(),
      description: z.string(),
      dtype: z.enum(["doc", "ui"]),
      layout: z.string(),
    }),
  ),
});
async function getModule(module: string) {
  // TODO check if module is a valid module
  const text = await cached(`gnome-module-${module}`, () =>
    fetch(`https://l10n.gnome.org/api/v1/modules/${module}`, { headers }),
  );
  return Module.parse(JSON.parse(text));
}
/** Return list of all language codes. */
async function getLanguages() {
  const text = await cached(`gnome-languages`, () =>
    fetch(`https://l10n.gnome.org/api/v1/languages/`, { headers }),
  );
  return z
    .array(z.object({ name: z.string(), locale: z.string() }))
    .parse(JSON.parse(text))
    .map((x) => x.locale);
}
async function moduleDefaultBranch(module: string) {
  return (await getModule(module)).branches[0]?.name;
}

/**
 * Download PO file for `module` in `language` to the right place under CWD.
 * This always downloads file for the default branch of the module.
 * `domain` specifies the domain, either "po" (UI) or "help" (docs).
 */
async function downloadModule(
  module: string,
  language: string,
  domain: "po" | "help" = "po",
) {
  assert((await getModules()).includes(module));
  assert((await getLanguages()).includes(language));
  const branch = await moduleDefaultBranch(module);
  assert(branch);

  // eg. https://l10n.gnome.org/POT/gnome-terminal.gtk3/gnome-terminal.gtk3.zh_TW.po
  const res = await fetch(
    // For UI: https://l10n.gnome.org/POT/epiphany.main/epiphany.main.zh_TW.po
    // For help: https://l10n.gnome.org/module/po/epiphany/main/help/zh_TW.po
    domain === "po"
      ? `https://l10n.gnome.org/POT/${module}.${branch}/${module}.${branch}.${language}.po`
      : `https://l10n.gnome.org/module/po/${module}/${branch}/help/${language}.po`,
    { headers },
  );
  writeFileSync(
    // like zh_TW/po/epiphany.po or ja/help/epiphany.po
    `${language}/${domain}/${module}.po`,
    new Uint8Array(await res.arrayBuffer()),
  );
}

/**
 * Download template file for `module` to the right place under CWD.
 * This always downloads file for the default branch of the module.
 * `domain` specifies the domain, either "po" (UI) or "help" (docs).
 */
async function downloadModuleTemplate(
  module: string,
  domain: "po" | "help" = "po",
) {
  assert((await getModules()).includes(module));
  const branch = await moduleDefaultBranch(module);
  assert(branch);

  // eg. https://l10n.gnome.org/POT/gnome-terminal.gtk3/gnome-terminal.gtk3.pot
  const res = await fetch(
    `https://l10n.gnome.org/POT/${module}.${branch}/${module}.${branch}.pot`,
    { headers },
  );
  writeFileSync(
    `templates/${domain}/${module}.pot`,
    new Uint8Array(await res.arrayBuffer()),
  );
}

program
  .command("get-modules")
  .description("Show module list")
  .action(async () => {
    for (const module of await getModules()) {
      console.log(module);
    }
  });
program
  .command("get-module")
  .description("Get data about a module")
  .argument("<module>", "Module name")
  .action(async (module) => {
    console.log(`Default branch: ${await moduleDefaultBranch(module)}`);
    console.log("Other data:");
    console.log(await getModule(module));
  });

// Ignore top level errors
// If we pipe output to less then quit it without viewing the whole
// thing, the pager doesn't consume the entire pipe, which leads to a
// BrokenPipe error.
// This is the overkill but fast way to get rid of it.
program.parseAsync().catch(() => {});
